# Generated by Django 5.2 on 2025-04-04 14:41

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sektör Adı')),
            ],
            options={
                'verbose_name': 'Sektör',
                'verbose_name_plural': 'Sektörler',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('primary_color', colorfield.fields.ColorField(default='#0077b6', image_field=None, max_length=25, samples=None, verbose_name='Ana Renk')),
                ('secondary_color', colorfield.fields.ColorField(default='#023e8a', image_field=None, max_length=25, samples=None, verbose_name='İkincil Renk')),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Metin Rengi')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='catalog.sector', verbose_name='Sektör')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Resim')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat')),
                ('show_price', models.BooleanField(default=True, verbose_name='Fiyat Göster')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirimli Fiyat')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stok')),
                ('show_stock', models.BooleanField(default=False, verbose_name='Stok Göster')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Resim')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ana Resim')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Resmi',
                'verbose_name_plural': 'Ürün Resimleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Özellik Adı')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.sector', verbose_name='Sektör')),
            ],
            options={
                'verbose_name': 'Ürün Özelliği',
                'verbose_name_plural': 'Ürün Özellikleri',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Değer')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productfeature', verbose_name='Özellik')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Özellik Değeri',
                'verbose_name_plural': 'Ürün Özellik Değerleri',
                'unique_together': {('product', 'feature')},
            },
        ),
    ]
