# Generated by Django 5.2 on 2025-04-04 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Referans URL')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='İlk Ziyaret')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Son Ziyaret')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='Ziyaret Sayısı')),
            ],
            options={
                'verbose_name': 'Ziyaretçi',
                'verbose_name_plural': 'Ziyaretçiler',
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Görüntüleme Zamanı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.product', verbose_name='Ürün')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='catalog.visitor', verbose_name='Ziyaretçi')),
            ],
            options={
                'verbose_name': 'Ürün Görüntüleme',
                'verbose_name_plural': 'Ürün Görüntülemeleri',
                'indexes': [models.Index(fields=['product', 'timestamp'], name='catalog_pro_product_6ef107_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Görüntüleme Zamanı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.category', verbose_name='Kategori')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_views', to='catalog.visitor', verbose_name='Ziyaretçi')),
            ],
            options={
                'verbose_name': 'Kategori Görüntüleme',
                'verbose_name_plural': 'Kategori Görüntülemeleri',
                'indexes': [models.Index(fields=['category', 'timestamp'], name='catalog_cat_categor_d2625d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ziyaret Zamanı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='catalog.company', verbose_name='Firma')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_visits', to='catalog.visitor', verbose_name='Ziyaretçi')),
            ],
            options={
                'verbose_name': 'Katalog Ziyareti',
                'verbose_name_plural': 'Katalog Ziyaretleri',
                'indexes': [models.Index(fields=['company', 'timestamp'], name='catalog_cat_company_252b87_idx')],
            },
        ),
    ]
